baseURL = "https://oj.boiltask.com/"
languageCode = "zh-CN"
title = "Online Judge Problem"
theme = "oj-problem"

[outputFormats.Problem]
mediaType = "text/html"
baseName = "index"
path = "problem"
isHTML = true
notAlternative = true

[outputFormats.Markdown]
mediaType = "text/markdown"
baseName = "index"
path = "markdown"
isPlainText = true
notAlternative = true

[outputFormats.Widget]
mediaType = "text/html"
baseName = "index"
path = "widget"
isHTML = true
notAlternative = true

[outputs]
page = ["HTML", "Problem", "Markdown", "Widget"]

[permalinks]
problem = ":slug"
page = ":slug"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
        unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[params]
  math = true
